-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."candidateUsers"
(
    user_id integer NOT NULL,
    name character varying(50) NOT NULL,
    surname character varying(50) NOT NULL,
    national_identity character varying(11) NOT NULL,
    birth_year character varying(4) NOT NULL,
    mail_verify boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."employerUsers"
(
    user_id integer NOT NULL,
    company_name character varying NOT NULL,
    web_adress character varying NOT NULL,
    phone_number character varying NOT NULL,
    mail_verify boolean NOT NULL,
    user_confirm "char" NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    "position" character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."staffUsers"
(
    user_id integer NOT NULL,
    name character varying NOT NULL,
    surname character varying NOT NULL,
    mail_verify boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    mail character varying(50) NOT NULL,
    password character varying(15) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."candidateUsers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public."employerUsers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public."staffUsers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;
